In [3]:
import tensorflow as tf
import os

In [24]:
os.environ['TF_CPP_MIN_LOG_LEVEL']=2

TypeError: str expected, not int

In [17]:
x=tf.constant(4.0,shape=(2,4), dtype= tf.float32 )
print(x)

tf.Tensor(
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]], shape=(2, 4), dtype=float32)


In [22]:
x=tf.constant ([[1,2,3],[4,5,6]])

In [19]:
x = tf.ones((2,2))

In [20]:
x = tf.zeros((2,2))

In [21]:
x=tf.eye(3)

In [23]:
a = tf.constant([1,2,3], dtype= tf.int32)
b = tf.constant([4,5,6], dtype= tf.int32)
c = tf.add(a,b)
print(c)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [30]:
c = tf.subtract(a,b)
print(c)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [32]:
c = tf.multiply(a,b)
print(c)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [33]:
c = tf.divide(a,b)
print(c)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
